#!/bin/bash
docker stop ratdeos1
docker stop ratdeos1-net
docker stop ratdeos2
docker stop ratdeos2-net
docker stop ratdeos3
docker stop ratdeos3-net
docker stop ratdeos4
docker stop ratdeos4-net
docker stop ratdeos5
docker stop ratdeos5-net
docker stop ratdeos6
docker stop ratdeos6-net
docker stop ratdeos7
docker stop ratdeos7-net
docker stop ratdeos8
docker stop ratdeos8-net
docker stop ratdeos9
docker stop ratdeos9-net
docker stop ratdeos10
docker stop ratdeos10-net
docker stop ratdeos11
docker stop ratdeos11-net
docker stop ratdeos12
docker stop ratdeos12-net
docker stop ratdeos13
docker stop ratdeos13-net
docker stop ratdeos14
docker stop ratdeos14-net
docker stop ratdeos15
docker stop ratdeos15-net
docker stop ratdeos16
docker stop ratdeos16-net
docker stop ratdeos17
docker stop ratdeos17-net
docker stop ratdeos18
docker stop ratdeos18-net
docker stop ratdeos19
docker stop ratdeos19-net
docker stop ratdeos20
docker stop ratdeos20-net
